version: '2'

services:
  db:
    image: postgres:9.4
    ports:
      - "5432"
  api:
    build: ./watchlist-api
    command: >
      sh -c '
      ./wait-for-it.sh -t 600 db:5432;
      rake db:drop;
      rake db:create;
      rake db:migrate;
      rake db:seed;
      rm ./tmp/pids/server.pid;
      bundle exec rails s -b 0.0.0.0
      '
    volumes:
      - ./watchlist-api:/api_volume
    links:
      - db
    depends_on:
      - db
    ports:
      - "2345:3000"
